name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    # Checkout source code
    - name: Checkout Code
      uses: actions/checkout@v4


    # Configure AWS credentials
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4

      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region: ap-south-1


    # Upload website files to S3
    - name: Upload files to S3
      run: |

        aws s3 sync ./ \
        s3://kalyan-github-actions-bucket \
        --delete \
        --exclude ".git/*" \
        --exclude ".github/*"



    # Deploy Docker container on EC2
    - name: Deploy Docker Container

      uses: appleboy/ssh-action@v1.0.3

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ${{ secrets.EC2_USERNAME }}

        key: ${{ secrets.EC2_SSH_KEY }}


        script: |


          echo "Login Docker Hub"

          docker login \
          -u ${{ secrets.DOCKER_USERNAME }} \
          -p ${{ secrets.DOCKER_TOKEN }}



          echo "Pull latest Docker image"

          docker pull kalyansagar5/furniture-app:latest



          echo "Stopping old container"

          docker stop furniture-container || true



          echo "Removing old container"

          docker rm furniture-container || true



          echo "Starting new container"

          docker run -d \
          --restart always \
          -p 8080:80 \
          --name furniture-container \
          kalyansagar5/furniture-app:latest



          echo "Deployment completed"



          docker ps
